version: "3.8"
services:
  backend:
    build: ./gis_backend
    ports:
      - "3030:3030"
    volumes:
      - ./gis_backend:/usr/src/app
    networks:
      - app-net

  frontend:
    build: ./gis_vista
    ports:
      - "7777:7777"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
